#FSR Autogenerated Content. DO NOT DELETE
from .create_ticket import create_ticket
from .get_ticket_information import get_ticket_information
from .list_tickets import list_tickets
from .add_comment import add_comment
from .update_ticket import update_ticket
from .delete_ticket import delete_ticket
 
supported_operations = {
	'create_ticket': create_ticket, 
	'get_ticket_information': get_ticket_information, 
	'list_tickets': list_tickets, 
	'add_comment': add_comment,
	'update_ticket': update_ticket,
	'delete_ticket': delete_ticket
}