#FSR Autogenerated Content. DO NOT DELETE
from .sample_get import sample_get
from .sample_put import sample_put
from .sample_post import sample_post
from .sample_delete import sample_delete
 
supported_operations = {
	'sample_get': sample_get, 
	'sample_put': sample_put, 
	'sample_post': sample_post, 
	'sample_delete': sample_delete
}
