# Generated by Django 3.1 on 2021-01-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postman', '0002_agent_allow_remote_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_name', models.CharField(max_length=500)),
                ('uuid', models.CharField(max_length=500, unique=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.agent', to_field='agent_id')),
            ],
        ),
    ]
