#FSR Autogenerated Content. DO NOT DELETE
from .query_ip import query_ip
from .query_domain import query_domain
from .query_url import query_url
from .query_file_reputation import query_file_reputation
 
supported_operations = {
	'query_ip': query_ip, 
	'query_domain': query_domain, 
	'query_url': query_url, 
	'query_file_reputation': query_file_reputation
}